CREATE TABLE users(
idUsers			INT (11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
uidUsers		TINYTEXT NOT NULL,
emailUsers		TINYTEXT NOT NULL,
pwd 			LONGTEXT NOT NULL
);

INSERT INTO users VALUES (1, 'TEST', 'TEST','TEST');